name: Ultimate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Ultimate Snakes
        uses: Platane/snk@v3
        with:
          github_user_name: sanyam-katoch10
          outputs: |
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake-light.svg?palette=github-light
            dist/github-snake-neon1.svg?palette=github-dark&color_snake=#A855F7
            dist/github-snake-neon2.svg?palette=github-dark&color_snake=#22D3EE
            dist/github-snake-neon3.svg?palette=github-dark&color_snake=#FACC15

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
